### ISSUE TITLE
Crash on close

### ISSUE THREAD

**Issue by ApostolosB** [Obsidian-StudiosInc/ecrire#32]
##### Description
Description of issue

App crashes on close

##### Steps to reproduce

1. Open ecrire
2. Type something
3. Close from the X on the top bar
4. Hit discard.

##### System information
- EFL Version = git
- E Version = git
- X or Wayland = Wayland

**Comment by wltjr** [comment]
Issues are to be expected against git till next release. I likely need to update build system to prevent build against git. I do not run efl or e from git, and have no plans to do such for testing. To many things break in git. A week or so ago E was broken due to efl git changes. Still seems work is being done there. Maybe check closer to an actual release. They should be working towards one, but some large commit drop that caused issues may have set that back.

**Comment by wltjr** [comment]
I am seeing this as well. I believe I know where the problem resides. Result of a change to move towards tabs. Making a global variable local. When you go to close, it may not have the right local variable, or it was lost along the way. Not sure exactly, but it is [this exact line causing](https://github.com/Obsidian-StudiosInc/ecrire/blob/v0.3.1/src/bin/main.c#L576) the issue, based on the value being passed. I will see about resolving ASAP.

**Comment by wltjr** [comment]
Looks like this maybe a issue in EFL 1.21. This does not happen in EFL 1.20. In EFL 1.21 Ecrire segfaults on close of open document via window border X, main menu close, or toolbar close. Rather than close the document and exit normally, close entire UI, Ecrire segfaults.

@ajwillia-ms, @haxworx please see the following back trace. This only happens with an open document. When you go to close via any means, X on window border, or either close from main menu or toolbar in Ecrire. Unless something changed in elm_code and I am not closing the document properly. I do not think that to be the case, as new document works fine. As in, you have an open document, you select new from main menu or toolbar. Which then closes the current document and opens a new one. That works fine so the closing and opening file is fine in elm_code/ecrire.

This seems to only happen when your closing the entire UI/application with an open document. It maybe relate to some other change in EFL. I am seeing lots of applications having issues with termination under 1.21. Ecrire without a open document, will output things under 1.21 it did not under 1.20. Same with others like etui.

```
#0  0x00007ffff7452f10 in eina_unicode_utf8_next_get (iindex=0x7fffffffc5b4,
    buf=0x7fffe8665000 <error: Cannot access memory at address 0x7fffe8665000>)
    at ../src/lib/eina/eina_inline_unicode.x:43
#1  _elm_code_widget_line_text_column_width_to_position (obj=0x4000000df4b0,
    pd=<optimized out>, line=<optimized out>, position=44)
    at lib/elementary/elm_code_widget_text.c:138
#2  0x00007ffff7453011 in _elm_code_widget_line_text_column_width_get (
    obj=<optimized out>, pd=<optimized out>, line=<optimized out>)
    at lib/elementary/elm_code_widget_text.c:157
#3  0x00007ffff744d832 in elm_obj_code_widget_line_text_column_width_get (
    obj=obj@entry=0x4000000df4b0, line=0x555555f30270)
    at lib/elementary/elm_code_widget.eo.c:172
#4  0x00007ffff7450205 in elm_code_widget_line_text_column_width_get (
    obj=obj@entry=0x4000000df4b0, line=<optimized out>)
    at lib/elementary/elm_code_widget.eo.c:522
#5  0x00007ffff745157b in _elm_code_widget_resize (
    widget=widget@entry=0x4000000df4b0, newline=newline@entry=0x0)
    at lib/elementary/elm_code_widget.c:1999
#6  0x00007ffff74520dc in _elm_code_widget_fill_update (
    widget=widget@entry=0x4000000df4b0, first_row=1, last_row=32,
    newline=newline@entry=0x0) at lib/elementary/elm_code_widget.c:499
#7  0x00007ffff74521b2 in _elm_code_widget_refresh (widget=0x4000000df4b0,
    line=0x0) at lib/elementary/elm_code_widget.c:538
#8  0x00007ffff7bcb9e7 in _event_callback_call (legacy_compare=1 '\001',
    event_info=<optimized out>, desc=<optimized out>, pd=0x555555ee85b0,
    obj_id=<optimized out>) at lib/eo/eo_base_class.c:1698
#9  _efl_object_event_callback_legacy_call (obj_id=<optimized out>,
    pd=0x555555ee85b0, desc=<optimized out>, event_info=<optimized out>)
    at lib/eo/eo_base_class.c:1771
#10 0x00007ffff7bc6057 in efl_event_callback_legacy_call (obj=0x4000000df4b0,
    desc=0x555555eece00, event_info=0x0) at lib/eo/eo_base_class.c:1774
#11 0x00007ffff7bc6057 in efl_event_callback_legacy_call (obj=0x4000000df4b0,
    desc=0x555555eece00, event_info=0x0) at lib/eo/eo_base_class.c:1774
#12 0x00007ffff7bcb5bf in _event_callback_call (legacy_compare=0 '\000',
    event_info=<optimized out>,
    desc=0x7ffff78fe480 <_EFL_UI_FOCUS_OBJECT_EVENT_FOCUS_CHANGED>,
    pd=0x555555ee85b0, obj_id=<optimized out>) at lib/eo/eo_base_class.c:1698
#13 _efl_object_event_callback_call (obj_id=<optimized out>,
    pd=0x555555ee85b0,
    desc=0x7ffff78fe480 <_EFL_UI_FOCUS_OBJECT_EVENT_FOCUS_CHANGED>,
    event_info=<optimized out>) at lib/eo/eo_base_class.c:1759
#14 0x00007ffff7bc5f57 in efl_event_callback_call (obj=0x4000000df4b0,
    desc=0x7ffff78fe480 <_EFL_UI_FOCUS_OBJECT_EVENT_FOCUS_CHANGED>,
    event_info=0x1) at lib/eo/eo_base_class.c:1762
#15 0x00007ffff7bc5f57 in efl_event_callback_call (obj=0x4000000df4b0,
    desc=0x7ffff78fe480 <_EFL_UI_FOCUS_OBJECT_EVENT_FOCUS_CHANGED>,
    event_info=0x1) at lib/eo/eo_base_class.c:1762
#16 0x00007ffff75f250f in efl_ui_focus_object_focus_set (obj=0x4000000df4b0,
    focus=focus@entry=1 '\001') at lib/elementary/efl_ui_focus_object.eo.c:17
#17 0x00007ffff75aefa2 in _efl_ui_widget_efl_ui_focus_object_focus_set (
    obj=0x4000000df4b0, pd=<optimized out>, focus=<optimized out>)
    at lib/elementary/efl_ui_widget.c:5696
#18 0x00007ffff75f250f in efl_ui_focus_object_focus_set (obj=0x4000000df4b0,
    focus=focus@entry=1 '\001') at lib/elementary/efl_ui_focus_object.eo.c:17
#19 0x00007ffff75eddeb in _efl_ui_focus_manager_calc_efl_ui_focus_manager_redirect_set (obj=0x400000009156, pd=0x555555a28a40, redirect=0x0)
    at lib/elementary/efl_ui_focus_manager_calc.c:796
#20 0x00007ffff75ec38f in efl_ui_focus_manager_redirect_set (
    obj=0x400000009156, redirect=redirect@entry=0x0)
    at lib/elementary/efl_ui_focus_manager.eo.c:13
#21 0x00007ffff75efa28 in _efl_ui_focus_manager_calc_efl_ui_focus_manager_manager_focus_set (obj=0x400000009156, pd=<optimized out>, focus=<optimized out>)
    at lib/elementary/efl_ui_focus_manager_calc.c:1359
#22 0x00007ffff75ec1af in efl_ui_focus_manager_focus_set (obj=0x40000000654b,
    focus=0x4000000df4b0) at lib/elementary/efl_ui_focus_manager.eo.c:11
#23 0x00007ffff75f648d in _efl_ui_focus_layer_enable_set (obj=0x400000021db9,
    pd=0x555555d969a0, v=<optimized out>)
    at lib/elementary/efl_ui_focus_layer.c:142
#24 0x00007ffff75f5f8f in efl_ui_focus_layer_enable_set (obj=0x400000021db9,
    v=<optimized out>) at lib/elementary/efl_ui_focus_layer.eo.c:4
#25 0x00007ffff30cb98f in efl_gfx_entity_visible_set (obj=0x400000021db9,
    v=v@entry=0 '\000') at ../src/lib/efl/interfaces/efl_gfx_entity.eo.c:15
#26 0x00007ffff74d6243 in _elm_hover_efl_gfx_entity_visible_set (
    obj=0x400000021db9, pd=<optimized out>, vis=<optimized out>)
    at lib/elementary/elm_hover.c:662
#27 0x00007ffff30cb98f in efl_gfx_entity_visible_set (obj=0x400000021db9,
    v=<optimized out>) at ../src/lib/efl/interfaces/efl_gfx_entity.eo.c:15
#28 0x00007ffff6345aa0 in _eo_evas_object_cb (data=0x555555d9a420,
    event=0x7fffffffcfa0) at lib/evas/canvas/evas_callbacks.c:184
#29 0x00007ffff7bcb9e7 in _event_callback_call (legacy_compare=1 '\001',
    event_info=<optimized out>, desc=<optimized out>, pd=0x55555594c730,
    obj_id=<optimized out>) at lib/eo/eo_base_class.c:1698
#30 _efl_object_event_callback_legacy_call (obj_id=<optimized out>,
    pd=0x55555594c730, desc=<optimized out>, event_info=<optimized out>)
    at lib/eo/eo_base_class.c:1771
#31 0x00007ffff7bc6057 in efl_event_callback_legacy_call (obj=0x40000000654b,
    desc=0x7ffff33042c0 <_EFL_GFX_ENTITY_EVENT_HIDE>, event_info=0x0)
    at lib/eo/eo_base_class.c:1774
#32 0x00007ffff7bc6057 in efl_event_callback_legacy_call (
    obj=obj@entry=0x40000000654b,
    desc=desc@entry=0x7ffff33042c0 <_EFL_GFX_ENTITY_EVENT_HIDE>,
    event_info=event_info@entry=0x0) at lib/eo/eo_base_class.c:1774
#33 0x00007ffff634639d in evas_object_event_callback_call (
    eo_obj=0x40000000654b, obj=obj@entry=0x55555594c780,
    type=type@entry=EVAS_CALLBACK_HIDE, event_info=event_info@entry=0x0,
    event_id=event_id@entry=45050,
    efl_event_desc=0x7ffff33042c0 <_EFL_GFX_ENTITY_EVENT_HIDE>)
    at lib/evas/canvas/evas_callbacks.c:413
#34 0x00007ffff6384e2d in evas_object_inform_call_hide (
    eo_obj=<optimized out>, obj=0x55555594c780)
    at lib/evas/canvas/evas_object_inform.c:21
#35 0x00007ffff30cb98f in efl_gfx_entity_visible_set (obj=0x40000000654b,
    v=v@entry=0 '\000') at ../src/lib/efl/interfaces/efl_gfx_entity.eo.c:15
#36 0x00007ffff638f3f2 in _efl_canvas_group_efl_gfx_entity_visible_set (
    eo_obj=0x40000000654b, o=0x55555594c8b0, vis=<optimized out>)
    at lib/evas/canvas/evas_object_smart.c:873
#37 0x00007ffff30cb98f in efl_gfx_entity_visible_set (obj=0x40000000654b,
    v=v@entry=0 '\000') at ../src/lib/efl/interfaces/efl_gfx_entity.eo.c:15
#38 0x00007ffff75af697 in _efl_ui_widget_efl_gfx_entity_visible_set (
    obj=0x40000000654b, pd=0x55555594c940, vis=<optimized out>)
    at lib/elementary/efl_ui_widget.c:965
#39 0x00007ffff30cb98f in efl_gfx_entity_visible_set (obj=0x40000000654b,
    v=v@entry=0 '\000') at ../src/lib/efl/interfaces/efl_gfx_entity.eo.c:15
#40 0x00007ffff75c48da in _efl_ui_win_hide (sd=0x55555594cae0,
    obj=0x40000000654b) at lib/elementary/efl_ui_win.c:2413
#41 _efl_ui_win_efl_gfx_entity_visible_set (obj=0x40000000654b,
    sd=0x55555594cae0, vis=<optimized out>) at lib/elementary/efl_ui_win.c:2449
#42 0x00007ffff30cb98f in efl_gfx_entity_visible_set (
    obj=obj@entry=0x40000000654b, v=v@entry=0 '\000')
    at ../src/lib/efl/interfaces/efl_gfx_entity.eo.c:15
#43 0x00007ffff637f572 in _efl_canvas_object_efl_object_invalidate (
    eo_obj=0x40000000654b, obj=0x55555594c780)
    at lib/evas/canvas/evas_object_main.c:1250
#44 0x00007ffff7bc6fa7 in efl_invalidate (obj=0x40000000654b)
    at lib/eo/efl_object.eo.c:72
#45 0x00007ffff7bc6fa7 in efl_invalidate (obj=0x40000000654b)
    at lib/eo/efl_object.eo.c:72
#46 0x00007ffff7bccdb4 in _efl_invalidate (obj=obj@entry=0x55555594c6f0)
    at lib/eo/eo_base_class.c:171
#47 0x00007ffff7bcd575 in _efl_object_parent_set (obj=0x40000000654b,
    pd=0x55555594c730, parent_id=0x0) at lib/eo/eo_base_class.c:735
#48 0x00007ffff7bc614f in efl_parent_set (obj=obj@entry=0x40000000654b,
    parent=parent@entry=0x0) at lib/eo/efl_object.eo.c:12
#49 0x00007ffff7bcd715 in efl_del (obj=0x40000000654b)
    at lib/eo/eo_base_class.c:687
#50 0x00007ffff75c2493 in _elm_win_delete_request (ee=<optimized out>)
    at lib/elementary/efl_ui_win.c:3110
#51 0x00007fffe78a4519 in _ecore_evas_x_event_window_delete_request (
    data=<optimized out>, type=<optimized out>, event=0x5555560bf1e0)
    at modules/ecore_evas/engines/x/ecore_evas_x.c:1786
#52 0x00007ffff6ddd4d8 in _ecore_event_message_handler_efl_loop_message_handler_message_call (obj=0x400000001537, pd=0x5555557b8b80, message=0x4000000f5ad1)
    at lib/ecore/ecore_event_message_handler.c:359
#53 0x00007ffff6de46ef in efl_loop_message_handler_message_call (
    obj=0x400000001537, message=0x4000000f5ad1)
    at lib/ecore/efl_loop_message_handler.eo.c:14
#54 0x00007ffff6de0671 in _efl_loop_message_process (obj=<optimized out>,
    pd=0x5555557b17e0) at lib/ecore/efl_loop.c:633
#55 0x00007ffff6ddf12b in efl_loop_message_process (
    obj=obj@entry=0x400000000132) at lib/ecore/efl_loop.c:663
#56 0x00007ffff6dd9e31 in _ecore_main_loop_iterate_internal (
    obj=obj@entry=0x400000000132, pd=pd@entry=0x5555557b17e0,
    once_only=once_only@entry=0) at lib/ecore/ecore_main.c:2450
#57 0x00007ffff6dda655 in _ecore_main_loop_begin (obj=0x400000000132,
    pd=pd@entry=0x5555557b17e0) at lib/ecore/ecore_main.c:1183
#58 0x00007ffff6de0589 in _efl_loop_begin (obj=<optimized out>,
    pd=0x5555557b17e0) at lib/ecore/efl_loop.c:83
#59 0x00007ffff6ddf40e in efl_loop_begin (obj=0x400000000132)
    at lib/ecore/efl_loop.eo.c:28
#60 0x00007ffff6dda707 in ecore_main_loop_begin ()
    at lib/ecore/ecore_main.c:1266
#61 0x000055555556181f in elm_main (argc=1, argv=0x7fffffffdb98)
    at ../src/bin/main.c:1090
#62 0x0000555555561944 in main (argc=1, argv=0x7fffffffdb98)
    at ../src/bin/main.c:1100
```

**Comment by wltjr** [comment]
Think this is ecrire specific. It does not happen if you use close from the toolbar, which closes an open document and exits ecrire. But if you hit exit from main menu or from window border close button, it segfaults. Only on EFL 1.21-beta1 not EFL 1.20.7 for what ever reason.

**Comment by wltjr** [comment]
This should be resolved now. Please test and close if the issue is resolved, thank you!

**Comment by ApostolosB** [comment]
Yep.
