### ISSUE TITLE
Crash with selected text

### ISSUE THREAD

**Issue by ApostolosB** [Obsidian-StudiosInc/ecrire#60]
##### Description
Description of issue
On many occasions having an area of text selected (one two lines) and clicking somewhere else leads to a crash.

##### Steps to reproduce
1. Select some text
2. Click somewhere else
3. Crash (once every 5-6 times)
...

##### System information
- EFL Version > 1.24.3
- E Version > 0.24.2
- X or Wayland > Wayland

BT:
```
(gdb) bt
#0  0x00007fe92a092a50 in free () from /usr/lib/libc.so.6
#1  0x00007fe92a352b38 in evas_object_textgrid_row_clear (r=0x562b68370030, o=0x562b67bf3108) at ../src/lib/evas/canvas/evas_object_textgrid.c:159
#2  0x00007fe92a354cb4 in evas_object_textgrid_rows_clear (eo_obj=eo_obj@entry=0x400000265498) at ../src/lib/evas/canvas/evas_object_textgrid.c:191
#3  0x00007fe92a356510 in _evas_textgrid_grid_size_set (eo_obj=0x400000265498, o=0x562b67bf3108, w=156, h=1) at ../src/lib/evas/canvas/evas_object_textgrid.c:900
#4  0x00007fe92a350aeb in evas_obj_textgrid_grid_size_set (obj=obj@entry=0x400000265498, w=156, h=h@entry=1) at ../src/lib/evas/canvas/evas_textgrid_eo.c:12
#5  0x00007fe92a356906 in evas_object_textgrid_size_set (obj=obj@entry=0x400000265498, w=<optimized out>, h=h@entry=1)
    at ../src/lib/evas/canvas/evas_textgrid_eo.legacy.c:17
#6  0x00007fe92a726a7e in _elm_code_widget_resize (widget=widget@entry=0x400000164428, newline=newline@entry=0x0) at ../src/lib/elementary/elm_code_widget.c:2099
#7  0x00007fe92a7276db in _elm_code_widget_fill_update (newline=0x0, last_row=618, first_row=557, widget=0x400000164428) at ../src/lib/elementary/elm_code_widget.c:514
#8  _elm_code_widget_refresh (widget=0x400000164428, line=0x0) at ../src/lib/elementary/elm_code_widget.c:553
#9  0x00007fe929d61743 in _event_callback_call (obj_id=0x400000166430, pd=0x562b6798ce90, desc=0x562b679cea00, event_info=<optimized out>, legacy_compare=<optimized out>)
    at ../src/lib/eo/eo_base_class.c:2139
#10 0x00007fe929d5b3e1 in efl_event_callback_legacy_call (obj=0x400000166430, desc=0x562b679cea00, event_info=0x0) at ../src/lib/eo/eo_base_class.c:2215
#11 0x00007fe92a7f47b6 in _elm_interface_scrollable_content_pos_set (obj=0x400000166430, sid=0x562b6798d2d8, x=0, y=8369, sig=<optimized out>)
    at ../src/lib/elementary/elm_interface_scrollable.c:1733
#12 0x00007fe92a7eca11 in elm_interface_scrollable_content_pos_set (obj=0x400000166430, x=0, y=8369, sig=sig@entry=1 '\001')
    at src/lib/elementary/elm_interface_scrollable.eo.c:390
#13 0x00007fe92a7f2d0f in _elm_scroll_scroll_to_y_animator (data=0x562b6798d2d8, event=<optimized out>) at ../src/lib/elementary/elm_interface_scrollable.c:2540
#14 0x00007fe929d61743 in _event_callback_call (obj_id=0x400000166430, pd=0x562b6798ce90, desc=0x7fe92a466f80 <_EFL_CANVAS_OBJECT_EVENT_ANIMATOR_TICK>,
    event_info=<optimized out>, legacy_compare=<optimized out>) at ../src/lib/eo/eo_base_class.c:2139
#15 0x00007fe929d5b3e1 in efl_event_callback_legacy_call (obj=0x400000166430, desc=0x7fe92a466f80 <_EFL_CANVAS_OBJECT_EVENT_ANIMATOR_TICK>, event_info=0x7fffc3dd6a90)
    at ../src/lib/eo/eo_base_class.c:2215
#16 0x00007fe929d61743 in _event_callback_call (obj_id=0x40000000dacb, pd=0x562b673872c0, desc=0x7fe92a466f80 <_EFL_CANVAS_OBJECT_EVENT_ANIMATOR_TICK>,
    event_info=<optimized out>, legacy_compare=<optimized out>) at ../src/lib/eo/eo_base_class.c:2139
#17 0x00007fe929d5b2e1 in efl_event_callback_call (obj=0x40000000dacb, desc=0x7fe92a466f80 <_EFL_CANVAS_OBJECT_EVENT_ANIMATOR_TICK>,
    event_info=event_info@entry=0x7fffc3dd6a90) at ../src/lib/eo/eo_base_class.c:2203
#18 0x00007fe929d2f048 in ecore_evas_animator_tick (ee=0x562b673518b0, viewport=<optimized out>, loop_time=29440.949381031998) at ../src/lib/ecore_evas/ecore_evas.c:3146
#19 0x00007fe929a50405 in _frame_cb (data=0x562b67353170, callback=<optimized out>, timestamp=29440947) at ../src/lib/ecore_wl2/ecore_wl2_window.c:1504
#20 0x00007fe928ecaa8d in ?? () from /usr/lib/libffi.so.7
#21 0x00007fe928eca01b in ?? () from /usr/lib/libffi.so.7
#22 0x00007fe929a3be92 in ?? () from /usr/lib/libwayland-client.so.0
#23 0x00007fe929a386c1 in ?? () from /usr/lib/libwayland-client.so.0
#24 0x00007fe929a39ccc in wl_display_dispatch_queue_pending () from /usr/lib/libwayland-client.so.0
#25 0x00007fe929a58c48 in _cb_connect_data (data=0x562b67345160, hdl=0x562b671039f0) at ../src/lib/ecore_wl2/ecore_wl2_display.c:569
#26 0x00007fe92a50d43b in _ecore_call_fd_cb (fd_handler=0x562b671039f0, data=<optimized out>, func=<optimized out>) at ../src/lib/ecore/ecore_private.h:506
#27 _ecore_main_fd_handlers_call (obj=0x400000000295, pd=0x562b670fe058) at ../src/lib/ecore/ecore_main.c:2124
#28 _ecore_main_loop_iterate_internal (obj=obj@entry=0x400000000295, pd=pd@entry=0x562b670fe058, once_only=once_only@entry=0) at ../src/lib/ecore/ecore_main.c:2501
#29 0x00007fe92a50da55 in _ecore_main_loop_begin (obj=obj@entry=0x400000000295, pd=pd@entry=0x562b670fe058) at ../src/lib/ecore/ecore_main.c:1210
#30 0x00007fe92a512486 in _efl_loop_begin (obj=0x400000000295, pd=0x562b670fe058) at ../src/lib/ecore/efl_loop.c:57
#31 0x00007fe92a511751 in efl_loop_begin (obj=0x400000000295) at src/lib/ecore/efl_loop.eo.c:28
#32 0x00007fe92a50db09 in ecore_main_loop_begin () at ../src/lib/ecore/ecore_main.c:1295
#33 0x0000562b66d7574b in elm_main (argv=0x7fffc3dd7158, argc=2) at /usr/src/debug/ecrire/src/bin/main.c:1421
#34 elm_main (argc=2, argv=0x7fffc3dd7158) at /usr/src/debug/ecrire/src/bin/main.c:1365
#35 0x0000562b66d7304f in main (argc=2, argv=0x7fffc3dd7158) at /usr/src/debug/ecrire/src/bin/main.c:1431
(gdb)
```
And another one:

https://www.enlightenment.org/ss/display.php?image=e-5f1f45fa39c0d6.84108689.jpg

**Comment by wltjr** [comment]
Hi, thanks for the report. This might be an upstream issue in EFL. It might also be Wayland specific, as I tried to replicate but I was not successful. Although, I see from your report, that the problem is not consistent, so I might not still experience it at some point. If possible, can you try it out under X11 to see if it crashes there. Thanks!
